from __future__ import annotations

from dataclasses import dataclass

from app.schemas.query import ObservationInput, StructuredQuery

from query_engine.context.resolver import ContextResolver
from query_engine.context.schemas import (
    ContextResolutionResult,
    ConversationContext,
)

from query_engine.embedding.encoder import MultilingualE5Encoder
from query_engine.embedding.schemas import EmbeddingResult

from query_engine.entities.extractor import EntityExtractor
from query_engine.entities.schemas import ExtractionResult

from query_engine.intent.classifier import (
    ClassificationResult,
    IntentClassifier,
)

from query_engine.language.detector import detect_language
from query_engine.language.schemas import LanguageResult

from query_engine.router.task_router import (
    TaskRouter,
    TaskRoutingResult,
)

from query_engine.structured_query.builder import StructuredQueryBuilder


@dataclass(frozen=True)
class QueryEngineResult:
    """
    Complete result produced by the Query Engine pipeline.
    """

    language: LanguageResult
    embedding: EmbeddingResult
    classification: ClassificationResult
    extraction: ExtractionResult
    context_resolution: ContextResolutionResult
    routing: TaskRoutingResult
    structured_query: StructuredQuery


class QueryEngine:
    """
    Main Query Engine pipeline.

    Pipeline:

        User Query
            ↓
        Language Identification
            ↓
        Multilingual-E5 Embedding
            ↓
        Intent Classification
            ↓
        Entity / Slot Extraction
            ↓
        Context Resolution
            ↓
        Task Routing
            ↓
        StructuredQuery
    """

    def __init__(
        self,
        embedding_encoder: MultilingualE5Encoder | None = None,
        intent_classifier: IntentClassifier | None = None,
        entity_extractor: EntityExtractor | None = None,
        context_resolver: ContextResolver | None = None,
        task_router: TaskRouter | None = None,
        structured_query_builder: StructuredQueryBuilder | None = None,
    ) -> None:

        self.embedding_encoder = (
            embedding_encoder
            or MultilingualE5Encoder()
        )

        self.intent_classifier = (
            intent_classifier
            or IntentClassifier(
                encoder=self.embedding_encoder
            )
        )

        self.entity_extractor = (
            entity_extractor
            or EntityExtractor()
        )

        self.context_resolver = (
            context_resolver
            or ContextResolver()
        )

        self.task_router = (
            task_router
            or TaskRouter()
        )

        self.structured_query_builder = (
            structured_query_builder
            or StructuredQueryBuilder()
        )

    def process(
        self,
        question: str,
        *,
        request_id: str,
        context: ConversationContext | None = None,
        inputs: list[ObservationInput] | None = None,
        modality: str | None = None,
    ) -> QueryEngineResult:
        """
        Process a user query through the complete Query Engine.

        Parameters
        ----------
        question:
            User's textual query.

        request_id:
            Request identifier generated by the API/request
            lifecycle layer.

        context:
            Current conversation observation context.

        inputs:
            Explicit observation inputs attached to the request.

        modality:
            Optional modality supplied by the request layer.

        Returns
        -------
        QueryEngineResult
            Complete output of the Query Engine pipeline.
        """

        # ---------------------------------------------------------
        # Input validation
        # ---------------------------------------------------------

        if not isinstance(question, str):
            raise TypeError("question must be a string")

        if not question.strip():
            raise ValueError("question cannot be empty")

        if not isinstance(request_id, str):
            raise TypeError("request_id must be a string")

        if not request_id.strip():
            raise ValueError("request_id cannot be empty")

        # ---------------------------------------------------------
        # 1. Language Identification
        # ---------------------------------------------------------

        language = detect_language(question)

        # ---------------------------------------------------------
        # 2. Multilingual-E5 Embedding
        # ---------------------------------------------------------

        embedding = self.embedding_encoder.encode(question)

        # ---------------------------------------------------------
        # 3. Intent Classification
        # ---------------------------------------------------------

        classification = self.intent_classifier.classify(
            question
        )

        # ---------------------------------------------------------
        # 4. Entity / Slot Extraction
        # ---------------------------------------------------------

        extraction = self.entity_extractor.extract(
            question
        )

        # ---------------------------------------------------------
        # 5. Context Resolution
        # ---------------------------------------------------------

        resolved_context = (
            context
            if context is not None
            else ConversationContext()
        )

        context_resolution = (
            self.context_resolver.resolve(
                question,
                resolved_context,
            )
        )

        # ---------------------------------------------------------
        # 6. Task Routing
        # ---------------------------------------------------------

        routing = self.task_router.route(
            classification.intent
        )

        # ---------------------------------------------------------
        # 7. StructuredQuery Construction
        # ---------------------------------------------------------

        structured_query = (
            self.structured_query_builder.build(
                request_id=request_id,
                question=question,
                intent=classification.intent.value,
                extraction=extraction,
                context_resolution=context_resolution,
                routing=routing,
                inputs=inputs,
                modality=modality,
            )
        )

        # ---------------------------------------------------------
        # Final Result
        # ---------------------------------------------------------

        return QueryEngineResult(
            language=language,
            embedding=embedding,
            classification=classification,
            extraction=extraction,
            context_resolution=context_resolution,
            routing=routing,
            structured_query=structured_query,
        )